# Generated by Django 4.0.1 on 2022-01-19 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_errorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='session',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='place_of_error',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.session'),
        ),
    ]
